name: territory_capture_app
description: A Flutter app for capturing territories by walking

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  firebase_crashlytics: ^4.1.2
  firebase_analytics: ^11.0.0
  firebase_remote_config: ^5.1.0
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  get: ^4.6.6
  geolocator: ^13.0.1
  permission_handler: ^11.3.1 
  dartz: ^0.10.1
  intl: ^0.20.2
  rename: ^3.1.0
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true